name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Setup just
        uses: extractions/setup-just@v2

      - name: Check coverage
        run: just coverage

      - name: Setup GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: '~> v2'
          install-only: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Setup npm
        run: npm install --global npm@11.5.1

      - name: Build snapshot release
        run: goreleaser release --snapshot --clean

      - name: Validate npm packages
        run: node scripts/test-npm-packages.js --version 0.0.0-test.0
